user_email_selector=xpath://input[@placeholder='Enter Username']
user_password_selector=xpath://input[@placeholder=' Enter Password']
login_button_selector=xpath://button[@type='submit']

error_message_selector=xpath://div[@class='p-toast-detail ng-tns-c21-1']

forgot_password=xpath://u[normalize-space()='Forgot Password']
user_forgot_passowrd=xpath://input[@placeholder='Enter Username'][1]
forgot_text=xpath://h3[normalize-space()='Forgot Password']
forgot_submit=xpath://button[@type='submit']
forgot_error=xpath://div[@class='p-toast-detail ng-tns-c21-2']
home=xpath://button[@id='login_signup_cancel']

email=xpath://input[@placeholder='Enter Email']
forgot_username=xpath://u[normalize-space()='Forgot Username']

signup=xpath://u[normalize-space()='Sign Up']