user_email_selector=xpath://input[@placeholder='Enter Username']
user_password_selector=xpath://input[@placeholder=' Enter Password']
login_button_selector=xpath://button[@type='submit']

error_message_selector=xpath://div[@class='p-toast-detail ng-tns-c21-1']

forgot_password=xpath://u[normalize-space()='Forgot Password']
user_forgot_passowrd=xpath://input[@placeholder='Enter Username'][1]
forgot_text=xpath://h3[normalize-space()='Forgot Password']
forgot_submit=xpath://button[@type='submit']
forgot_error=xpath://div[@class='p-toast-detail ng-tns-c21-2']
home=xpath://button[@id='login_signup_cancel']

email=xpath://input[@placeholder='Enter Email']
forgot_username=xpath://u[normalize-space()='Forgot Username']

signup=xpath://u[normalize-space()='Sign Up']

# Manage_officer menu
//officer_menu=xpath://a[@class='lia dropdown-toggle active collapsed']
//officer_menu=xpath://span[contains(text(),'Officers')]
//officer_menu=xpath://div[@id='sidebar-wrapper']//a[.='Officers']
officer_menu=xpath://div[@id='sidebar-wrapper']//ul[@class='sidebar-nav']/li[5]
manage_officer=xpath://a[normalize-space()='Manage Officers']
//add_officer=xpath://button[@class='btn c-or-blue-outline-btn mt-3 ng-star-inserted']
add_officer=xpath://button[@routerlink="/officers/manage-officer/add-officer"]
# Officer Details Form
officer_firstname=xpath://input[@formcontrolname='firstName']
officer_lastname=xpath://input[@formcontrolname='lastName']
officer_email=xpath://input[@formcontrolname='email']
officer_phonenumber=xpath://input[@formcontrolname='phone']
offiecer_employeeNumber=xpath://input[@formcontrolname='employeeNumber']
officer_userName=xpath://input[@formcontrolname='userName']
officer_password=xpath://input[@formcontrolname='password']
officer_confirmPassword=xpath://input[@formcontrolname='confirmPassword']
officer_address1=xpath://input[@formcontrolname='address1']
officer_address2=xpath://input[@formcontrolname='address2']
officer_city=xpath://input[@formcontrolname='city']
officer_state=xpath://input[@formcontrolname='state']
officer_country=xpath://select[@formcontrolname='country']
officer_postalcode=xpath://input[@formcontrolname='postalCode']
officer_branch=xpath://select[@formcontrolname='branch']
officer_applycheckbox=xpath://input[@formcontrolname='hasCustomerPortalAccess']
officer_supervisor=xpath://input[@formcontrolname='isSupervisor']
officer_upload_photo=xpath://button[normalize-space()='Upload Photo']
officer_submit=xpath://div[@class='ml-2 row show_btn']//button[@type='button'][normalize-space()='Submit']
officer_cancel=xpath://div[@class='ml-2 row show_btn']//button[@type='button'][normalize-space()='Cancel']


# Edit officer app

edit_offficer=xpath://i[@class='fa fa-pencil']
delete_officer=xpath://i[@class='fa fa-trash']
alert_ok=xpath://button[text()=' Ok ']
alert_cancel=xpath://button[text()=' Cancel ']
reset_password_officer=xpath://i[@class='fa fa-key']
new_password=xpath://input[@formcontrolname='newPassword']
password_submit=xpath://button[@type='button'][normalize-space()='Submit']
password_cancel=xpath://button[normalize-space()='Cancel']




